gateway:
  dynamic:
    route:
      serverAddr: 47.108.95.212:8848
      nameSpace: f19a013a-3e81-437d-892e-d3b8bc604177
      dataId: gateway-route-dev.json
      group: DEFAULT_GROUP
spring:
  redis:
    host: 47.108.95.212
    port: 6379
    password: 981109
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wfh
    password: 981109
    url: jdbc:mysql://47.108.95.212:3306/shopping-user?serverTimezone=UTC
mybatis-plus:
  type-aliases-package: com.wfh.shopping.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
shopping:
  jwt:
    expire-time: 30